# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  geoip-dat = {
    pname = "geoip-dat";
    version = "202205022212";
    src = fetchurl {
      url = "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/download/202205022212/geoip.dat";
      sha256 = "sha256-UmIgU12Tte6goa5/dsKOyq6JKdEi4bbzbfyL8eKUp2g=";
    };
  };
  geosite-dat = {
    pname = "geosite-dat";
    version = "202205022212";
    src = fetchurl {
      url = "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/download/202205022212/geosite.dat";
      sha256 = "sha256-YRSmGtY7Y6tfeJ10i3JnVf5H7T5pM1Tt/4mqnMo5KX8=";
    };
  };
  mosdns = {
    pname = "mosdns";
    version = "v3.7.3";
    src = fetchFromGitHub ({
      owner = "IrineSistiana";
      repo = "mosdns";
      rev = "v3.7.3";
      fetchSubmodules = false;
      sha256 = "sha256-ZywhZxsib3rnIzrkrjAKpV9sRE0PCFXeHB1NJ6/tKCg=";
    });
  };
  v2ray = {
    pname = "v2ray";
    version = "v5.0.5";
    src = fetchFromGitHub ({
      owner = "v2fly";
      repo = "v2ray-core";
      rev = "v5.0.5";
      fetchSubmodules = false;
      sha256 = "sha256-xelzsV0l6d4m8ufaIGbC3sE+M6F1ILR5N4vOEiqEfmU=";
    });
  };
}
