# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  geoip-dat = {
    pname = "geoip-dat";
    version = "202204302211";
    src = fetchurl {
      url = "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/download/202204302211/geoip.dat";
      sha256 = "sha256-UmIgU12Tte6goa5/dsKOyq6JKdEi4bbzbfyL8eKUp2g=";
    };
  };
  geosite-dat = {
    pname = "geosite-dat";
    version = "202204302211";
    src = fetchurl {
      url = "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/download/202204302211/geosite.dat";
      sha256 = "sha256-vZ9M/M6s97xhiTFIY8cwcAaMoqQaShtv2xfhSnDWDq8=";
    };
  };
  mosdns = {
    pname = "mosdns";
    version = "v3.7.3";
    src = fetchFromGitHub ({
      owner = "IrineSistiana";
      repo = "mosdns";
      rev = "v3.7.3";
      fetchSubmodules = false;
      sha256 = "sha256-ZywhZxsib3rnIzrkrjAKpV9sRE0PCFXeHB1NJ6/tKCg=";
    });
  };
  v2ray = {
    pname = "v2ray";
    version = "v5.0.3";
    src = fetchFromGitHub ({
      owner = "v2fly";
      repo = "v2ray-core";
      rev = "v5.0.3";
      fetchSubmodules = false;
      sha256 = "sha256-a/yYGf9VRxuXiv0kveB9SOxSPCnkF5m8/KbCoOb9jok=";
    });
  };
}
